unclassified:
  location:
    url: http://localhost:8080/

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
          - id: "${JENKINS_ADMIN_ID}"
            password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    globalMatrix:
      entries:
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Administer"
        - user:
            name: "anonymous"
            permissions:
              - "Overall/Read"

  nodes:
    - permanent:
        labelString: "elixir otp"
        launcher: "inbound"
        name: "tumbleweed-elixir-1"
        nodeDescription: "Tumbleweed based elixir agent"
        numExecutors: 2
        remoteFS: "/home/jenkins/agent"
        retentionStrategy: "always"

jobs:
  - file: /var/jenkins_home/jenkins-seed.yaml

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              description: "ssh-key to access git@tuxedo-xps from jenkins"
              id: "ssh-key-tuxedo-xps-git"
              passphrase: "${JENKINS_GIT_SSH_KEY_PASSPHRASE}"
              # "{AQAAABAAAAAgPrNatDwI1htukd5maqPQ+5hPehGFmrlk8HWAGsX2Zgz6nyzFfjJnqzEIdHwwmc3h}"
              privateKeySource:
                directEntry:
                  privateKey: "${JENKINS_GIT_SSH_KEY}"
              scope: GLOBAL
              username: "git"
