unclassified:
  location:
    url: http://localhost:8080/

jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
          - id: "${JENKINS_ADMIN_ID}"
            password: "${JENKINS_ADMIN_PASSWORD}"

  authorizationStrategy:
    globalMatrix:
      entries:
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Administer"
        - user:
            name: "anonymous"
            permissions:
              - "Overall/Read"

  nodes:
    - permanent:
        labelString: "elixir otp"
        launcher: "inbound"
        name: "tumbleweed-elixir-1"
        nodeDescription: "Tumbleweed based elixir agent"
        numExecutors: 2
        remoteFS: "/home/jenkins/agent"
        retentionStrategy: "always"

jobs:
  - file: /var/jenkins_home/jenkins-seed.yaml


