name: mj-inventory-v2

services:
  jenkins:
    image: "jenkins/jenkins:2.478-jdk21"
    ports:
      - "8080:8080"
    environment:
      JENKINS_JAVA_OPTS: -Djenkins.install.runSetupWizard=false -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      CASC_JENKINS_CONFIG: /var/jenkins_home/jenkins-configuration.yaml
      JENKINS_ADMIN_ID: mjansen
      JENKINS_ADMIN_PASSWORD: mjansen
      JENKINS_GIT_SSH_KEY_PASSPHRASE: ${JENKINS_GIT_SSH_KEY_PASSPHRASE}
      JENKINS_GIT_SSH_KEY: ${JENKINS_GIT_SSH_KEY}
    configs:
      - source: jenkins-jcac-config
        target: /var/jenkins_home/jenkins-configuration.yaml
      - source: jenkins-seed
        target: /var/jenkins_home/jenkins-seed.yaml
      - source: jenkins-plugins
        target: /usr/share/jenkins/ref/plugins.txt
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    extra_hosts:
      # host.docker.internal
      # host.gateway
      - "${HOSTNAME}=host-gateway"
    networks:
      - jenkins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
    depends_on:
      jenkins-plugin-update:
          condition: service_completed_successfully

  jenkins-agent-elixir:
    image: "jenkins-agent/tumbleweed-elixir"
    pull_policy: build
    build:
      context: "jenkins-agent"
      dockerfile: "tumbleweed-elixir/Dockerfile"
    command: > 
      -webSocket
      -secret 1e4e46d01f7c7a3d43030810cacec3b2138af4775048d60a18e86f8ec3b539db
      -name "tumbleweed-elixir-1"
      -url http://jenkins:8080
    stdin_open: true
    extra_hosts:
      # host.docker.internal
      # host.gateway
      - "${HOSTNAME}=host-gateway"
    networks:
      - jenkins
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
    depends_on:
      jenkins:
        condition: service_healthy

  jenkins-plugin-update:
    image: "jenkins/jenkins:2.478-jdk21"
    command: jenkins-plugin-cli --verbose --plugin-download-directory /var/jenkins_home/plugins --plugin-file /usr/share/jenkins/ref/plugins.txt
    restart: no
    configs:
      - source: jenkins-plugins
        target: /usr/share/jenkins/ref/plugins.txt
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
    networks:
      - jenkins

configs:
  jenkins-jcac-config:
    file: ./jenkins/jcac-config.yaml
  jenkins-plugins:
    file: ./jenkins/plugins.txt
  jenkins-seed:
    file: ./jenkins/seed.groovy

volumes:
  jenkins_home:

networks:
  jenkins:
