name: CI

on: push

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} / NodeJS ${{matrix.nodejs}}

    # Michael Jansen 2012/03/04 setup-elixir doesn't work with ubuntu 20.04 right now
    # error: Package libwxgtk3.0-0v5 is not available, but is referred to by another package.
    # reason: package was renamed from libwxgtk3.0-dev to libwxgtk3.0-gtk3-dev from 18 to 20
    # issue: https://github.com/erlef/setup-elixir/issues/6
    # runs-on: ubuntu-latest
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        otp: [ '23.2.1' ]
        elixir: [ '1.11.2' ]
        nodejs: [ '12.x' ]

    steps:

      #
      ### CHECKOUT
      - name: Checkout Sources
        uses: actions/checkout@v2

      #
      ### SETUP VERSIONS
      - name: Setup Elixir
        # https://github.com/erlef/setup-elixir
        uses: erlef/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodejs}}

      #
      ### SETUP/CACHE DEPENDENCIES
      - name: Cache dependencies
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: |
              deps/
              _build/dev/dialyxir*.plt
              _build/dev/dialyxir*.plt.hash
          key: ${{ runner.os }}-${{ matrix.otp}}-${{matrix.elixir}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix local.rebar --force
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix local.hex --force
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.get
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.deps-cache.outputs.cache-hit != 'true'

      #
      ### SETUP/CACHE NODE STUFF
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: apps/inventory_web/assets/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/inventory_web/assets/package-lock.json')) }}
      - run: npm install --prefix assets
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        working-directory: apps/inventory_web

      #
      ### BUILD OUR NPM STUFF
      - run: npm run deploy --prefix assets
        working-directory: apps/inventory_web
      - run: mix phx.digest
        working-directory: apps/inventory_web

      #
      ### BUILD
      - run: mix compile
      - run: mix docs
      - name: Run mix credo
        run: |
          mix credo || (
          rc=$?

          # Only fail on warnings
          if (( $rc & 0x10 )) ; then
          echo "We have warnings"
          exit 1;
          fi
          )

      #
      ### TEST
      - run: mix compile
        env:
          MIX_ENV: test

      - run: mix test
        env:
          MIX_ENV: test

      - run: mix test --cover
        env:
          MIX_ENV: test

      #
      ### DIALYZER
      # we cached this as part of the dependencies above
      - if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          mix dialyzer --plt

      - run: mix dialyzer --no-check --halt-exit-status
